name: coverage
on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

env:
  PROXY_HOST: ${{ secrets.PROXY_HOST }}
  PROXY_USER: ${{ secrets.PROXY_USER }}
  PROXY_PASS: ${{ secrets.PROXY_PASS }}
  PROXY_HOST_HTTPS: ${{ secrets.PROXY_HOST_HTTPS }}
  PROXY_PORT_HTTPS: ${{ secrets.PROXY_PORT_HTTPS }}
  PROXY_HOST_SOCKS5: ${{ secrets.PROXY_HOST_SOCKS5 }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Calc coverage
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov