name: tests
on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  pull_request:
    paths:
      - '**.go'
  schedule:
    # run tests regularly at 3 AM every days to check if CloudFlare updated their detection
    - cron: '0 3 * * *'

env:
  PROXY_HOST: ${{ secrets.PROXY_HOST }}
  PROXY_USER: ${{ secrets.PROXY_USER }}
  PROXY_PASS: ${{ secrets.PROXY_PASS }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...